apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pv.name }}
spec:
  capacity:
    storage: {{ .Values.persistence.pv.capacity }}
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.pv.hostPath }}
    type: Directory

